# Generated by Django 4.1.3 on 2022-12-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('ELEM', 'Elementary'), ('MIDD', 'MiddleSchool'), ('HIGH', 'Highschool')], default='ELEM', max_length=4),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='example.district'),
            preserve_default=False,
        ),
    ]
